using Godot;
using GEmuera.Core.Ports;
using GEmuera.Core.Session;
using System;
using System.Collections.Generic;

using VariantDictionary = Godot.Collections.Dictionary;

public enum PrototypeInputActionKind
{
    Unknown = 0,
    Pressed = 1,
    Released = 2,
    Moved = 3,
    Text = 4,
    Scroll = 5,
    Hover = 6,
    Submit = 7,
    Cancel = 8,
}

public enum PrototypeInputRequestKind
{
    EnterKey = 1,
    AnyKey = 2,
    IntValue = 3,
    StrValue = 4,
    Void = 5,
    AnyValue = 6,
    IntButton = 7,
    StrButton = 8,
    PrimitiveMouseKey = 11,
}

/// <summary>
/// Immutable input packet used by the Godot-side queue. Core receives only
/// the smaller NormalizedAction projection; Godot signals receive a Variant
/// dictionary generated by ToVariantDictionary().
/// </summary>
public sealed class PrototypeInputActionDto
{
    public const int UnboundPointerIndex = -1;

    public PrototypeInputActionDto(
        long generation,
        long requestId,
        long operationId,
        string actionId,
        InputDeviceKind device,
        PrototypeInputActionKind kind,
        Vector2 position = default,
        Vector2 delta = default,
        Vector2 velocity = default,
        PointerButton button = PointerButton.None,
        int pointerIndex = UnboundPointerIndex,
        int code = 0,
        int physicalCode = 0,
        string text = "",
        float factor = 0.0f,
        float pressure = 0.0f,
        bool pressed = false,
        bool echo = false,
        bool doubleClick = false)
    {
        if (string.IsNullOrWhiteSpace(actionId))
            throw new ArgumentException("Action id is required.", nameof(actionId));
        if (generation < 0)
            throw new ArgumentOutOfRangeException(nameof(generation));
        if (requestId < 0)
            throw new ArgumentOutOfRangeException(nameof(requestId));
        if (operationId < 0)
            throw new ArgumentOutOfRangeException(nameof(operationId));
        if (!float.IsFinite(position.X) || !float.IsFinite(position.Y))
            throw new ArgumentOutOfRangeException(nameof(position));

        Generation = generation;
        RequestId = requestId;
        OperationId = operationId;
        ActionId = actionId.Trim();
        Device = device;
        Kind = kind;
        Position = position;
        Delta = delta;
        Velocity = velocity;
        Button = button;
        PointerIndex = pointerIndex;
        Code = code;
        PhysicalCode = physicalCode;
        Text = text ?? string.Empty;
        Factor = factor;
        Pressure = pressure;
        Pressed = pressed;
        Echo = echo;
        DoubleClick = doubleClick;
    }

    public long Generation { get; }
    public long RequestId { get; }
    public long OperationId { get; }
    public string ActionId { get; }
    public InputDeviceKind Device { get; }
    public PrototypeInputActionKind Kind { get; }
    public Vector2 Position { get; }
    public Vector2 Delta { get; }
    public Vector2 Velocity { get; }
    public PointerButton Button { get; }
    public int PointerIndex { get; }
    public int Code { get; }
    public int PhysicalCode { get; }
    public string Text { get; }
    public float Factor { get; }
    public float Pressure { get; }
    public bool Pressed { get; }
    public bool Echo { get; }
    public bool DoubleClick { get; }

    public PrototypeInputActionDto WithOperationId(long operationId)
    {
        return new PrototypeInputActionDto(
            Generation,
            RequestId,
            operationId,
            ActionId,
            Device,
            Kind,
            Position,
            Delta,
            Velocity,
            Button,
            PointerIndex,
            Code,
            PhysicalCode,
            Text,
            Factor,
            Pressure,
            Pressed,
            Echo,
            DoubleClick);
    }

    public PrototypeInputActionDto WithRequestId(long requestId)
    {
        return new PrototypeInputActionDto(
            Generation,
            requestId,
            OperationId,
            ActionId,
            Device,
            Kind,
            Position,
            Delta,
            Velocity,
            Button,
            PointerIndex,
            Code,
            PhysicalCode,
            Text,
            Factor,
            Pressure,
            Pressed,
            Echo,
            DoubleClick);
    }

    public PrototypeInputActionDto WithIdentity(long generation, long requestId)
    {
        return new PrototypeInputActionDto(
            generation,
            requestId,
            OperationId,
            ActionId,
            Device,
            Kind,
            Position,
            Delta,
            Velocity,
            Button,
            PointerIndex,
            Code,
            PhysicalCode,
            Text,
            Factor,
            Pressure,
            Pressed,
            Echo,
            DoubleClick);
    }

    public NormalizedAction ToNormalizedAction()
    {
        if (OperationId <= 0)
            throw new InvalidOperationException("A Core action requires an operation id.");
        return new NormalizedAction(
            ActionId,
            Device,
            Position.X,
            Position.Y,
            Button,
            new SessionStamp(
                new SessionGeneration(Generation),
                new SessionOperationId(OperationId)));
    }

    public VariantDictionary ToVariantDictionary()
    {
        return new VariantDictionary
        {
            ["generation"] = Generation,
            ["request_id"] = RequestId,
            ["operation_id"] = OperationId,
            ["action_id"] = ActionId,
            ["device"] = (int)Device,
            ["device_name"] = Device.ToString(),
            ["kind"] = (int)Kind,
            ["kind_name"] = Kind.ToString(),
            ["position"] = Position,
            ["delta"] = Delta,
            ["velocity"] = Velocity,
            ["button"] = (int)Button,
            ["pointer_index"] = PointerIndex,
            ["code"] = Code,
            ["physical_code"] = PhysicalCode,
            ["text"] = Text,
            ["factor"] = Factor,
            ["pressure"] = Pressure,
            ["pressed"] = Pressed,
            ["echo"] = Echo,
            ["double_click"] = DoubleClick,
        };
    }

    public static PrototypeInputActionDto FromKeyboard(long generation, long requestId, InputEventKey @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        var keyName = @event.Keycode.ToString().ToLowerInvariant();
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            "key." + keyName,
            InputDeviceKind.Keyboard,
            @event.Pressed ? PrototypeInputActionKind.Pressed : PrototypeInputActionKind.Released,
            code: (int)@event.Keycode,
            physicalCode: (int)@event.PhysicalKeycode,
            text: ToUnicodeText(@event.Unicode),
            pressed: @event.Pressed,
            echo: @event.Echo);
    }

    public static PrototypeInputActionDto FromMouseButton(long generation, long requestId, InputEventMouseButton @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            "mouse." + @event.ButtonIndex.ToString().ToLowerInvariant(),
            InputDeviceKind.Mouse,
            @event.Pressed ? PrototypeInputActionKind.Pressed : PrototypeInputActionKind.Released,
            position: @event.Position,
            button: MapButton(@event.ButtonIndex),
            factor: @event.Factor,
            pressed: @event.Pressed,
            doubleClick: @event.DoubleClick);
    }

    public static PrototypeInputActionDto FromMouseMotion(long generation, long requestId, InputEventMouseMotion @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            "mouse.motion",
            InputDeviceKind.Mouse,
            PrototypeInputActionKind.Moved,
            position: @event.Position,
            delta: @event.Relative,
            velocity: @event.Velocity,
            button: PointerButton.None,
            code: (int)@event.ButtonMask);
    }

    public static PrototypeInputActionDto FromTouch(long generation, long requestId, InputEventScreenTouch @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            @event.Pressed ? "touch.down" : "touch.up",
            InputDeviceKind.Touch,
            @event.Pressed ? PrototypeInputActionKind.Pressed : PrototypeInputActionKind.Released,
            position: @event.Position,
            pointerIndex: @event.Index,
            pressed: @event.Pressed);
    }

    public static PrototypeInputActionDto FromTouchDrag(long generation, long requestId, InputEventScreenDrag @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            "touch.drag",
            InputDeviceKind.Touch,
            PrototypeInputActionKind.Moved,
            position: @event.Position,
            delta: @event.Relative,
            velocity: @event.Velocity,
            pointerIndex: @event.Index,
            pressure: @event.Pressure);
    }

    public static PrototypeInputActionDto FromAction(long generation, long requestId, InputEventAction @event)
    {
        ArgumentNullException.ThrowIfNull(@event);
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            @event.Action.ToString(),
            InputDeviceKind.Controller,
            @event.Pressed ? PrototypeInputActionKind.Pressed : PrototypeInputActionKind.Released,
            factor: @event.Strength,
            pressed: @event.Pressed);
    }

    public static PrototypeInputActionDto VirtualCursorMove(long generation, Vector2 position, Vector2 delta)
    {
        return new PrototypeInputActionDto(
            generation,
            0,
            0,
            "virtual_cursor.move",
            InputDeviceKind.VirtualCursor,
            PrototypeInputActionKind.Moved,
            position: position,
            delta: delta);
    }

    public static PrototypeInputActionDto VirtualCursorHover(long generation, Vector2 position)
    {
        return new PrototypeInputActionDto(
            generation,
            0,
            0,
            "virtual_cursor.hover",
            InputDeviceKind.VirtualCursor,
            PrototypeInputActionKind.Hover,
            position: position);
    }

    public static PrototypeInputActionDto VirtualCursorClick(
        long generation,
        long requestId,
        Vector2 position,
        int mouseButton,
        string actionId = "virtual_cursor.click")
    {
        return new PrototypeInputActionDto(
            generation,
            requestId,
            0,
            actionId,
            InputDeviceKind.VirtualCursor,
            PrototypeInputActionKind.Submit,
            position: position,
            button: MapButton(mouseButton),
            pressed: true);
    }

    private static PointerButton MapButton(MouseButton button)
    {
        return button switch
        {
            MouseButton.Left => PointerButton.Left,
            MouseButton.Right => PointerButton.Right,
            MouseButton.Middle => PointerButton.Middle,
            _ => PointerButton.None,
        };
    }

    private static PointerButton MapButton(int button)
    {
        return button switch
        {
            1 => PointerButton.Left,
            2 => PointerButton.Right,
            4 => PointerButton.Middle,
            _ => PointerButton.None,
        };
    }

    private static string ToUnicodeText(long unicode)
    {
        if (unicode <= 0 || unicode > 0x10ffff || (unicode >= 0xd800 && unicode <= 0xdfff))
            return string.Empty;
        return char.ConvertFromUtf32((int)unicode);
    }
}

public sealed class PrototypeInputRequestDto
{
    public PrototypeInputRequestDto(
        long generation,
        long requestId,
        PrototypeInputRequestKind kind,
        bool oneInput = false,
        bool noFocus = false,
        bool stopMesskip = false,
        bool isSystemInput = false,
        bool mouseInput = false,
        bool hasDefaultValue = false,
        long defaultIntValue = 0,
        string defaultStringValue = "",
        long timeLimitMilliseconds = -1,
        bool displayTime = false,
        string timeUpMessage = "",
        long createdAtMilliseconds = -1)
    {
        if (generation < 0)
            throw new ArgumentOutOfRangeException(nameof(generation));
        if (requestId <= 0)
            throw new ArgumentOutOfRangeException(nameof(requestId));
        Generation = generation;
        RequestId = requestId;
        Kind = kind;
        OneInput = oneInput;
        NoFocus = noFocus;
        StopMesskip = stopMesskip;
        IsSystemInput = isSystemInput;
        MouseInput = mouseInput;
        HasDefaultValue = hasDefaultValue;
        DefaultIntValue = defaultIntValue;
        DefaultStringValue = defaultStringValue ?? string.Empty;
        TimeLimitMilliseconds = timeLimitMilliseconds;
        DisplayTime = displayTime;
        TimeUpMessage = timeUpMessage ?? string.Empty;
        CreatedAtMilliseconds = createdAtMilliseconds;
    }

    public long Generation { get; }
    public long RequestId { get; }
    public PrototypeInputRequestKind Kind { get; }
    public PrototypeInputRequestKind InputType => Kind;
    public bool NeedValue => RequiresValue(Kind);
    public bool OneInput { get; }
    public bool NoFocus { get; }
    public bool StopMesskip { get; }
    public bool IsSystemInput { get; }
    public bool MouseInput { get; }
    public bool HasDefaultValue { get; }
    public long DefaultIntValue { get; }
    public string DefaultStringValue { get; }
    public long TimeLimitMilliseconds { get; }
    public bool DisplayTime { get; }
    public string TimeUpMessage { get; }
    public long CreatedAtMilliseconds { get; }

    public bool IsExpired(long nowMilliseconds)
    {
        return TimeLimitMilliseconds > 0
            && CreatedAtMilliseconds >= 0
            && nowMilliseconds - CreatedAtMilliseconds >= TimeLimitMilliseconds;
    }

    public PrototypeInputRequestDto WithCreatedAt(long createdAtMilliseconds)
    {
        return new PrototypeInputRequestDto(
            Generation,
            RequestId,
            Kind,
            OneInput,
            NoFocus,
            StopMesskip,
            IsSystemInput,
            MouseInput,
            HasDefaultValue,
            DefaultIntValue,
            DefaultStringValue,
            TimeLimitMilliseconds,
            DisplayTime,
            TimeUpMessage,
            createdAtMilliseconds);
    }

    public VariantDictionary ToVariantDictionary()
    {
        return new VariantDictionary
        {
            ["generation"] = Generation,
            ["request_id"] = RequestId,
            ["kind"] = (int)Kind,
            ["kind_name"] = Kind.ToString(),
            ["need_value"] = NeedValue,
            ["one_input"] = OneInput,
            ["no_focus"] = NoFocus,
            ["stop_messkip"] = StopMesskip,
            ["system_input"] = IsSystemInput,
            ["mouse_input"] = MouseInput,
            ["has_default_value"] = HasDefaultValue,
            ["default_int"] = DefaultIntValue,
            ["default_string"] = DefaultStringValue,
            ["time_limit_ms"] = TimeLimitMilliseconds,
            ["display_time"] = DisplayTime,
            ["time_up_message"] = TimeUpMessage,
            ["created_at_ms"] = CreatedAtMilliseconds,
        };
    }

    public static bool RequiresValue(PrototypeInputRequestKind kind)
    {
        return kind == PrototypeInputRequestKind.IntValue
            || kind == PrototypeInputRequestKind.StrValue
            || kind == PrototypeInputRequestKind.IntButton
            || kind == PrototypeInputRequestKind.StrButton
            || kind == PrototypeInputRequestKind.AnyValue
            || kind == PrototypeInputRequestKind.PrimitiveMouseKey;
    }
}

/// <summary>
/// Node-level input adapter. It keeps the Godot queue and Core generation
/// guard together while exposing only Variant-safe signal payloads.
/// </summary>
public partial class PrototypeInputBridge : Node
{
    public const long UnboundRequestId = 0;

    [Signal]
    public delegate void ActionNormalizedEventHandler(string actionId, long generation, long operationId, float x, float y, int button);

    [Signal]
    public delegate void ActionRejectedEventHandler(string reason);

    [Signal]
    public delegate void ActionQueuedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void RequestQueuedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void RequestPresentedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void RequestResolvedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void InputSubmittedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void InputSubmissionRejectedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void RequestRejectedEventHandler(VariantDictionary payload);

    [Signal]
    public delegate void GenerationChangedEventHandler(long generation);

    [Export]
    public int MaxActionQueueDepth = 512;

    [Export]
    public int MaxRequestQueueDepth = 64;

    [Export]
    public bool CaptureUnhandledInput = true;

    [Export]
    public bool ConsumeUnhandledInput = false;

    private readonly Queue<PrototypeInputActionDto> actionQueue = new();
    private readonly Queue<PrototypeInputRequestDto> requestQueue = new();
    private readonly Dictionary<long, PrototypeInputRequestDto> pendingRequests = new();
    private InputCoordinator coordinator;
    private SessionGeneration generation = new(1);
    private long nextOperation;
    private long nextRequestId;
    private long activeRequestId;
    private bool acceptingInput = true;

    public long CurrentGeneration => generation.Value;
    public long ActiveRequestId => activeRequestId;
    public int ActionQueueCount => actionQueue.Count;
    public int RequestQueueCount => requestQueue.Count;
    public int PendingRequestCount => pendingRequests.Count;
    public bool IsGenerationAttached => acceptingInput && coordinator is not null;

    public override void _Ready()
    {
        coordinator ??= new InputCoordinator(generation);
        acceptingInput = true;
        SetProcessUnhandledInput(true);
    }

    public override void _ExitTree()
    {
        DetachGeneration(generation.Value);
    }

    public override void _UnhandledInput(InputEvent @event)
    {
        if (!CaptureUnhandledInput || !acceptingInput || @event == null)
            return;
        if (!TryNormalizeInputEvent(@event, out var action))
            return;
        if (EnqueueAction(action) && ConsumeUnhandledInput)
            GetViewport()?.SetInputAsHandled();
    }

    public bool SubmitVirtualAction(string actionId, float x = 0, float y = 0, int button = 0)
    {
        return Submit(actionId, InputDeviceKind.VirtualCursor, x, y, MapButton(button));
    }

    public void AdvanceGeneration(long value)
    {
        var next = new SessionGeneration(value);
        if (next.Value <= generation.Value)
            throw new ArgumentOutOfRangeException(nameof(value));

        ApplyGeneration(next);
    }

    public bool AttachGeneration(long value)
    {
        var next = new SessionGeneration(value);
        if (next.Value < generation.Value)
            return false;
        if (next.Value > generation.Value)
        {
            ApplyGeneration(next);
            return true;
        }

        coordinator ??= new InputCoordinator(generation);
        acceptingInput = true;
        SetProcessUnhandledInput(true);
        return true;
    }

    public bool DetachGeneration(long value = -1)
    {
        long expectedGeneration = value < 0 ? generation.Value : value;
        if (expectedGeneration != generation.Value)
            return false;

        acceptingInput = false;
        SetProcessUnhandledInput(false);
        coordinator?.Dispose();
        coordinator = null;
        ClearQueues();
        return true;
    }

    private void ApplyGeneration(SessionGeneration next)
    {
        if (coordinator is null)
            coordinator = new InputCoordinator(next);
        else
            coordinator.AdvanceGeneration(next);
        generation = next;
        nextOperation = 0;
        ClearQueues();
        acceptingInput = true;
        SetProcessUnhandledInput(true);
        EmitSignal(SignalName.GenerationChanged, generation.Value);
    }

    private void ClearQueues()
    {
        actionQueue.Clear();
        requestQueue.Clear();
        pendingRequests.Clear();
        activeRequestId = UnboundRequestId;
    }

    public PrototypeInputRequestDto CreateRequest(
        PrototypeInputRequestKind kind,
        bool oneInput = false,
        bool noFocus = false,
        bool stopMesskip = false,
        bool isSystemInput = false,
        bool mouseInput = false,
        bool hasDefaultValue = false,
        long defaultIntValue = 0,
        string defaultStringValue = "",
        long timeLimitMilliseconds = -1,
        bool displayTime = false,
        string timeUpMessage = "")
    {
        return new PrototypeInputRequestDto(
            generation.Value,
            AllocateRequestId(),
            kind,
            oneInput,
            noFocus,
            stopMesskip,
            isSystemInput,
            mouseInput,
            hasDefaultValue,
            defaultIntValue,
            defaultStringValue,
            timeLimitMilliseconds,
            displayTime,
            timeUpMessage,
            GetMonotonicMilliseconds());
    }

    public bool TryEnqueueRequest(
        PrototypeInputRequestKind kind,
        out PrototypeInputRequestDto request,
        bool oneInput = false,
        bool noFocus = false,
        bool stopMesskip = false,
        bool isSystemInput = false,
        bool mouseInput = false,
        bool hasDefaultValue = false,
        long defaultIntValue = 0,
        string defaultStringValue = "",
        long timeLimitMilliseconds = -1,
        bool displayTime = false,
        string timeUpMessage = "")
    {
        request = CreateRequest(
            kind,
            oneInput,
            noFocus,
            stopMesskip,
            isSystemInput,
            mouseInput,
            hasDefaultValue,
            defaultIntValue,
            defaultStringValue,
            timeLimitMilliseconds,
            displayTime,
            timeUpMessage);
        if (EnqueueRequest(request))
            return true;
        request = null;
        return false;
    }

    public bool EnqueueRequest(PrototypeInputRequestDto request)
    {
        if (!acceptingInput)
            return RejectRequest(request, "bridge_detached");
        if (request == null)
            return RejectRequest(null, "null_request");
        if (request.Generation != generation.Value)
            return RejectRequest(request, "generation_mismatch");
        if (request.RequestId <= UnboundRequestId || pendingRequests.ContainsKey(request.RequestId))
            return RejectRequest(request, "request_id_duplicate_or_unbound");

        CompactRequestQueue();
        if (requestQueue.Count >= GetRequestQueueCapacity())
            return RejectRequest(request, "request_queue_full");
        if (request.CreatedAtMilliseconds < 0)
            request = request.WithCreatedAt(GetMonotonicMilliseconds());
        if (request.RequestId > nextRequestId)
            nextRequestId = request.RequestId;

        pendingRequests.Add(request.RequestId, request);
        requestQueue.Enqueue(request);
        EmitSignal(SignalName.RequestQueued, request.ToVariantDictionary());
        return true;
    }

    public bool TryDequeueRequest(out PrototypeInputRequestDto request)
    {
        while (requestQueue.Count > 0)
        {
            var candidate = requestQueue.Dequeue();
            if (!pendingRequests.ContainsKey(candidate.RequestId))
                continue;
            activeRequestId = candidate.RequestId;
            request = candidate;
            EmitSignal(SignalName.RequestPresented, request.ToVariantDictionary());
            return true;
        }

        request = null;
        return false;
    }

    public bool TryGetPendingRequest(long requestId, out PrototypeInputRequestDto request)
    {
        return pendingRequests.TryGetValue(requestId, out request);
    }

    public bool TryDequeueAction(out PrototypeInputActionDto action)
    {
        if (actionQueue.Count == 0)
        {
            action = null;
            return false;
        }
        action = actionQueue.Dequeue();
        return true;
    }

    public bool EnqueueAction(PrototypeInputActionDto action)
    {
        return SubmitAction(action);
    }

    public bool TrySubmit(PrototypeInputActionDto submission)
    {
        if (submission == null)
            return RejectSubmission(null, "null_submission");
        if (!acceptingInput)
            return RejectSubmission(submission, "bridge_detached");
        if (submission.Generation != generation.Value)
            return RejectSubmission(submission, "generation_mismatch");
        if (submission.RequestId <= UnboundRequestId)
            return RejectSubmission(submission, "request_id_unbound");
        if (!pendingRequests.TryGetValue(submission.RequestId, out var request))
            return RejectSubmission(submission, "request_not_pending_or_already_resolved");
        if (request.IsExpired(GetMonotonicMilliseconds()))
        {
            pendingRequests.Remove(request.RequestId);
            ClearActiveRequest(request.RequestId);
            EmitRequestResolved(request, "timed_out", null);
            return RejectSubmission(submission, "request_expired");
        }

        if (!SubmitAction(submission, out var acceptedSubmission))
            return false;
        pendingRequests.Remove(request.RequestId);
        ClearActiveRequest(request.RequestId);
        EmitSignal(SignalName.InputSubmitted, BuildSubmissionPayload(acceptedSubmission, request, "completed"));
        EmitRequestResolved(request, "completed", acceptedSubmission);
        return true;
    }

    public bool TrySubmitCurrent(long requestId, PrototypeInputActionDto action)
    {
        if (action == null)
            return RejectSubmission(null, "null_submission");
        return TrySubmit(action.WithIdentity(generation.Value, requestId));
    }

    public bool TryCancelRequest(long requestId)
    {
        return TryResolveRequest(requestId, "cancelled");
    }

    public bool TryTimeoutRequest(long requestId)
    {
        return TryResolveRequest(requestId, "timed_out");
    }

    public bool QueueKeyboardEvent(InputEventKey @event)
    {
        return EnqueueAction(PrototypeInputActionDto.FromKeyboard(generation.Value, activeRequestId, @event));
    }

    public bool QueueMouseButtonEvent(InputEventMouseButton @event)
    {
        return EnqueueAction(PrototypeInputActionDto.FromMouseButton(generation.Value, activeRequestId, @event));
    }

    public bool QueueMouseMotionEvent(InputEventMouseMotion @event)
    {
        return EnqueueAction(PrototypeInputActionDto.FromMouseMotion(generation.Value, activeRequestId, @event));
    }

    public bool QueueTouchEvent(InputEventScreenTouch @event)
    {
        return EnqueueAction(PrototypeInputActionDto.FromTouch(generation.Value, activeRequestId, @event));
    }

    public bool QueueTouchDragEvent(InputEventScreenDrag @event)
    {
        return EnqueueAction(PrototypeInputActionDto.FromTouchDrag(generation.Value, activeRequestId, @event));
    }

    public bool QueueVirtualCursorMove(Vector2 position, Vector2 delta)
    {
        return EnqueueAction(PrototypeInputActionDto.VirtualCursorMove(generation.Value, position, delta));
    }

    public bool QueueVirtualCursorMove(long actionGeneration, Vector2 position, Vector2 delta)
    {
        return EnqueueAction(PrototypeInputActionDto.VirtualCursorMove(actionGeneration, position, delta));
    }

    public bool QueueVirtualCursorHover(Vector2 position)
    {
        return EnqueueAction(PrototypeInputActionDto.VirtualCursorHover(generation.Value, position));
    }

    public bool TrySubmitVirtualCursorClick(long requestId, Vector2 position, int mouseButton, string actionId = "virtual_cursor.click")
    {
        return TrySubmit(PrototypeInputActionDto.VirtualCursorClick(
            generation.Value,
            requestId,
            position,
            mouseButton,
            actionId));
    }

    private bool Submit(string actionId, InputDeviceKind device, float x, float y, PointerButton button)
    {
        return SubmitAction(new PrototypeInputActionDto(
            generation.Value,
            activeRequestId,
            0,
            actionId,
            device,
            PrototypeInputActionKind.Submit,
            position: new Vector2(x, y),
            button: button,
            pressed: true));
    }

    private bool SubmitAction(PrototypeInputActionDto action)
    {
        return SubmitAction(action, out _);
    }

    private bool SubmitAction(PrototypeInputActionDto action, out PrototypeInputActionDto acceptedAction)
    {
        acceptedAction = null;
        if (action == null)
            return RejectAction(null, "null_action");
        if (!acceptingInput || coordinator is null)
            return RejectAction(action, "bridge_detached");
        if (action.Generation != generation.Value)
            return RejectAction(action, "generation_mismatch");
        if (action.RequestId != UnboundRequestId && !pendingRequests.ContainsKey(action.RequestId))
            return RejectAction(action, "request_not_pending");
        if (action.RequestId != UnboundRequestId
            && pendingRequests.TryGetValue(action.RequestId, out var request)
            && request.IsExpired(GetMonotonicMilliseconds()))
        {
            pendingRequests.Remove(action.RequestId);
            ClearActiveRequest(action.RequestId);
            EmitRequestResolved(request, "timed_out", null);
            return RejectAction(action, "request_expired");
        }
        if (actionQueue.Count >= GetActionQueueCapacity())
            return RejectAction(action, "action_queue_full");

        var operation = new SessionOperationId(System.Threading.Interlocked.Increment(ref nextOperation));
        acceptedAction = action.WithOperationId(operation.Value);
        var status = coordinator.Submit(acceptedAction.ToNormalizedAction());
        if (status != InputSubmissionStatus.Accepted)
        {
            acceptedAction = null;
            EmitSignal(SignalName.ActionRejected, status.ToString());
            EmitSignal(SignalName.InputSubmissionRejected, BuildRejectionPayload(status.ToString(), action));
            return false;
        }

        actionQueue.Enqueue(acceptedAction);
        EmitSignal(SignalName.ActionQueued, acceptedAction.ToVariantDictionary());
        EmitSignal(
            SignalName.ActionNormalized,
            acceptedAction.ActionId,
            acceptedAction.Generation,
            acceptedAction.OperationId,
            acceptedAction.Position.X,
            acceptedAction.Position.Y,
            (int)acceptedAction.Button);
        return true;
    }

    private bool TryNormalizeInputEvent(InputEvent @event, out PrototypeInputActionDto action)
    {
        var requestId = activeRequestId;
        if (@event is InputEventKey key)
        {
            action = PrototypeInputActionDto.FromKeyboard(generation.Value, requestId, key);
            return true;
        }
        if (@event is InputEventMouseButton mouseButton)
        {
            action = PrototypeInputActionDto.FromMouseButton(generation.Value, requestId, mouseButton);
            return true;
        }
        if (@event is InputEventMouseMotion mouseMotion)
        {
            action = PrototypeInputActionDto.FromMouseMotion(generation.Value, requestId, mouseMotion);
            return true;
        }
        if (@event is InputEventScreenTouch touch)
        {
            action = PrototypeInputActionDto.FromTouch(generation.Value, requestId, touch);
            return true;
        }
        if (@event is InputEventScreenDrag drag)
        {
            action = PrototypeInputActionDto.FromTouchDrag(generation.Value, requestId, drag);
            return true;
        }
        if (@event is InputEventAction inputAction)
        {
            action = PrototypeInputActionDto.FromAction(generation.Value, requestId, inputAction);
            return true;
        }

        action = null;
        return false;
    }

    private bool TryResolveRequest(long requestId, string state)
    {
        if (!acceptingInput || !pendingRequests.TryGetValue(requestId, out var request))
            return false;
        pendingRequests.Remove(requestId);
        ClearActiveRequest(requestId);
        EmitRequestResolved(request, state, null);
        return true;
    }

    private void EmitRequestResolved(PrototypeInputRequestDto request, string state, PrototypeInputActionDto action)
    {
        var payload = request.ToVariantDictionary();
        payload["state"] = state;
        if (action != null)
            payload["action"] = action.ToVariantDictionary();
        EmitSignal(SignalName.RequestResolved, payload);
    }

    private static VariantDictionary BuildSubmissionPayload(
        PrototypeInputActionDto action,
        PrototypeInputRequestDto request,
        string state)
    {
        return new VariantDictionary
        {
            ["generation"] = action.Generation,
            ["request_id"] = action.RequestId,
            ["operation_id"] = action.OperationId,
            ["state"] = state,
            ["action"] = action.ToVariantDictionary(),
            ["request"] = request.ToVariantDictionary(),
        };
    }

    private bool RejectAction(PrototypeInputActionDto action, string reason)
    {
        EmitSignal(SignalName.ActionRejected, reason);
        EmitSignal(SignalName.InputSubmissionRejected, BuildRejectionPayload(reason, action));
        return false;
    }

    private bool RejectSubmission(PrototypeInputActionDto action, string reason)
    {
        EmitSignal(SignalName.InputSubmissionRejected, BuildRejectionPayload(reason, action));
        return false;
    }

    private bool RejectRequest(PrototypeInputRequestDto request, string reason)
    {
        var payload = new VariantDictionary
        {
            ["accepted"] = false,
            ["reason"] = reason,
            ["generation"] = request?.Generation ?? generation.Value,
            ["active_generation"] = generation.Value,
            ["request_id"] = request?.RequestId ?? UnboundRequestId,
            ["active_request_id"] = activeRequestId,
        };
        if (request != null)
            payload["request"] = request.ToVariantDictionary();
        EmitSignal(SignalName.InputSubmissionRejected, payload);
        EmitSignal(SignalName.RequestRejected, payload);
        return false;
    }

    private VariantDictionary BuildRejectionPayload(string reason, PrototypeInputActionDto action)
    {
        var payload = new VariantDictionary
        {
            ["accepted"] = false,
            ["reason"] = reason,
            ["generation"] = action?.Generation ?? generation.Value,
            ["active_generation"] = generation.Value,
            ["request_id"] = action?.RequestId ?? UnboundRequestId,
            ["active_request_id"] = activeRequestId,
        };
        if (action != null)
            payload["action"] = action.ToVariantDictionary();
        return payload;
    }

    private void CompactRequestQueue()
    {
        if (requestQueue.Count == 0)
            return;
        var liveRequests = new Queue<PrototypeInputRequestDto>(requestQueue.Count);
        while (requestQueue.Count > 0)
        {
            var request = requestQueue.Dequeue();
            if (pendingRequests.ContainsKey(request.RequestId))
                liveRequests.Enqueue(request);
        }
        while (liveRequests.Count > 0)
            requestQueue.Enqueue(liveRequests.Dequeue());
    }

    private void ClearActiveRequest(long requestId)
    {
        if (activeRequestId == requestId)
            activeRequestId = UnboundRequestId;
    }

    private long AllocateRequestId()
    {
        if (nextRequestId == long.MaxValue)
            throw new InvalidOperationException("Input request id exhausted.");
        return ++nextRequestId;
    }

    private int GetActionQueueCapacity()
    {
        return Math.Max(1, MaxActionQueueDepth);
    }

    private int GetRequestQueueCapacity()
    {
        return Math.Max(1, MaxRequestQueueDepth);
    }

    private static long GetMonotonicMilliseconds()
    {
        return (long)Time.GetTicksMsec();
    }

    private static PointerButton MapButton(MouseButton button)
    {
        return button switch
        {
            MouseButton.Left => PointerButton.Left,
            MouseButton.Right => PointerButton.Right,
            MouseButton.Middle => PointerButton.Middle,
            _ => PointerButton.None,
        };
    }

    private static PointerButton MapButton(int button)
    {
        return button switch
        {
            1 => PointerButton.Left,
            2 => PointerButton.Right,
            4 => PointerButton.Middle,
            _ => PointerButton.None,
        };
    }
}
